# Statime Configuration for Dante PTP Follower Mode
# CRITICAL: Media Bridge must be a PTP FOLLOWER in the Dante network
# Requires teodly/statime:inferno-dev branch for PTPv1 support

loglevel = "info"

# PTP network configuration (Dante domain 0)
sdo-id = 0
domain = 0

# CRITICAL: Set lowest priority to never become master
# Dante hardware devices use 249, we use 251 to be lower
priority1 = 251
priority2 = 255

# Enable virtual system clock with usrvclock export for Inferno
virtual-system-clock = true
virtual-system-clock-base = "monotonic_raw"
usrvclock-export = true  # CRITICAL: Required for Inferno clock sync

# Network interface configuration
[[port]]
interface = "br0"  # Bridge interface for Media Bridge
network-mode = "ipv4"  # Dante uses IPv4

# Hardware timestamping (auto-detect)
hardware-clock = "auto"

# CRITICAL: Dante requires PTPv1 (NOT PTPv2!)
protocol-version = "PTPv1"