#ifndef NDI_BRIDGE_VERSION_H
#define NDI_BRIDGE_VERSION_H

#define NDI_BRIDGE_VERSION_MAJOR 1
#define NDI_BRIDGE_VERSION_MINOR 6
#define NDI_BRIDGE_VERSION_PATCH 3

#define NDI_BRIDGE_VERSION_STRING "1.6.3"
#define NDI_BRIDGE_VERSION NDI_BRIDGE_VERSION_STRING

// Build info
#ifdef _DEBUG
#define NDI_BRIDGE_BUILD_TYPE "Debug"
#else
#define NDI_BRIDGE_BUILD_TYPE "Release"
#endif

#ifdef _WIN32
#define NDI_BRIDGE_PLATFORM "Windows"
#elif __linux__
#define NDI_BRIDGE_PLATFORM "Linux"
#else
#define NDI_BRIDGE_PLATFORM "Unknown"
#endif

#ifdef _MSC_VER
#define NDI_BRIDGE_COMPILER "MSVC"
#elif defined(__GNUC__)
#define NDI_BRIDGE_COMPILER "GCC"
#elif defined(__clang__)
#define NDI_BRIDGE_COMPILER "Clang"
#else
#define NDI_BRIDGE_COMPILER "Unknown"
#endif

// Feature flags
#ifdef PLATFORM_WINDOWS
#define NDI_BRIDGE_HAS_MEDIA_FOUNDATION 1
#define NDI_BRIDGE_HAS_DECKLINK 1
#define NDI_BRIDGE_HAS_V4L2 0
#elif defined(PLATFORM_LINUX)
#define NDI_BRIDGE_HAS_MEDIA_FOUNDATION 0
#define NDI_BRIDGE_HAS_DECKLINK 0
#define NDI_BRIDGE_HAS_V4L2 1
#else
#define NDI_BRIDGE_HAS_MEDIA_FOUNDATION 0
#define NDI_BRIDGE_HAS_DECKLINK 0
#define NDI_BRIDGE_HAS_V4L2 0
#endif

#endif // NDI_BRIDGE_VERSION_H
