#ifndef NDI_BRIDGE_VERSION_H
#define NDI_BRIDGE_VERSION_H

#define NDI_BRIDGE_VERSION_MAJOR 1
#define NDI_BRIDGE_VERSION_MINOR 0
#define NDI_BRIDGE_VERSION_PATCH 3

#define NDI_BRIDGE_VERSION_STRING "1.0.3"
#define NDI_BRIDGE_VERSION "1.0.3"

#endif // NDI_BRIDGE_VERSION_H
