#ifndef NDI_BRIDGE_VERSION_H
#define NDI_BRIDGE_VERSION_H

#define NDI_BRIDGE_VERSION_MAJOR 1
#define NDI_BRIDGE_VERSION_MINOR 0
#define NDI_BRIDGE_VERSION_PATCH 1

#define NDI_BRIDGE_VERSION_STRING "1.0.1"
#define NDI_BRIDGE_VERSION "1.0.1"

#endif // NDI_BRIDGE_VERSION_H
